version: "3.8"

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    networks:
      - pterodactyl
    ports:
      - "8080:80"
    volumes:
      - ./panel_data:/var/www/html
    environment:
      - APP_URL=http://localhost:8080
      - TRUSTED_PROXIES=*

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    privileged: true
    networks:
      - pterodactyl
    ports:
      - "2022:2022"
      - "8081:8080"
    volumes:
      - ./wings_data:/var/lib/pterodactyl
    environment:
      - WINGS_PANEL_URL=http://localhost:8080
      - WINGS_TOKEN_ID=
      - WINGS_TOKEN_SECRET=

networks:
  pterodactyl:
    driver: bridge
